import { Inter } from "next/font/google";
import "./globals.css";

import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { ShoppingCartProvider } from "@/context/ShoppingCartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <ShoppingCartProvider>

          <div className="flex flex-col min-h-screen w-800 m-auto"  style={{maxWidth: "1300px"}}>
            <Nav />
            {children}
            <Footer />
          </div>

        </ShoppingCartProvider>
        
      </body>
    </html>
  );
}

export default RootLayout;
