import { Inter } from "next/font/google";
import "./globals.css";

import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { ShoppingCartProvider } from "@/context/ShoppingCartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <ShoppingCartProvider>

          <div className="flex flex-col min-h-screen">
            <Nav />
            {children}
            <Footer />
          </div>

        </ShoppingCartProvider>
        
      </body>
    </html>
  );
}
